---
title: "CS&SS 508 - Introduction to R for Social Scientists"
author: | 
  | [Breon Haskett](https://github.com/breonh) 
  | [University of Washington](https://soc.washington.edu/people/breon-haskett)
---



## Important links

* [Canvas Page (enrolled students only SP  2022)](https://canvas.uw.edu/courses/1551596)
* [Syllabus](https://breonh.github.io/csss_508/syllabus.html)
* [Homework Instructions](https://breonh.github.io/csss_508/homework.html) and grading rubric.
* [Peer Review Instructions](https://breonh.github.io/csss_508/peer_review.html) and suggestions for reading code.
* [Class Slack Channel](https://uwcsss508.slack.com/)
* [R and RStudio Installation Instructions](https://breonh.github.io/csss_508/installation.html)
* [Enabling Compilation of Packages](https://breonh.github.io/csss_508/compilation.html)
* [How to Read an R Help Page](https://socviz.co/appendix.html#a-little-more-about-r)

## Helpful resources

* [R for Data Science online](http://r4ds.had.co.nz/) textbook by Garrett Grolemund and Hadley Wickham. One of many good R texts available, but importantly it is free and focuses on the [`tidyverse`](http://tidyverse.org/) collection of R packages which form the backbone of this course.
* [Advanced R](http://adv-r.had.co.nz/) online textbook by Hadley Wickham. A great source for more in-depth and advanced R programming.
* [Chuck Lanfear's Introduction to R Workshop](https://youtu.be/HbFaPArTIjo), recorded Oct. 11, 2018, with [companion webpage](https://clanfear.github.io/Intro_R_Workshop/).
* [Chuck Lanfear's Intermediate R Workshop](https://youtu.be/pSWaOOniVBk), recorded Jan. 31, 2019, with [companion webpage](https://clanfear.github.io/Intermediate_R_Workshop/).
* [What They Forgot to Teach You About R](https://whattheyforgot.org/) by Jenny Bryan and Jim Hester. Great information on best practices for managing projects and R itself.
* [Teacups, Giraffes, and Statistics](https://tinystats.github.io/teacups-giraffes-and-statistics/index.html), an illustrated and interactive introduction to R and statistics.
* [The Epidemiologist R Handbook](https://epirhandbook.com/index.html), an online textbook introducing modern R approaches for epidemiology.






## Weekly lecture notes and links:

### 1. RStudio and R Markdown
 **Lecture for Week 1:**
 
   * [Install R and R Markdown!](https://breonh.github.io/csss_508/installation.html)
   
   * [Slides for Lecture 1: Course logistics, R/RStudio, and R Markdown](https://breonh.github.io/csss_508/lecture/week1/csss_508_week1_Rstudio_and_Rmarkdown.html)
       + [Companion R Script for Lecture 1 slides](https://raw.githubusercontent.com/breonh/breonh.github.io/main/csss_508/lecture/week1/within_week1_slides_rcode.R)
       + [PDF of Lecture 1 slides](https://breonh.github.io/csss_508/lecture/week1/csss_508_week1_Rstudio_and_Rmarkdown.pdf)
       + [Rmd for Lecture 1 slides](https://raw.githubusercontent.com/breonh/breonh.github.io/main/csss_508/lecture/week1/csss_508_week1_Rstudio_and_Rmarkdown.Rmd)
       
   **Lecture Recording: **
   
   [Youtube Link to Week 1 Lecture](https://youtu.be/kkX706chxlM)


   **Homework 1:**
       
   * **[Homework 1 Instructions](https://breonh.github.io/csss_508/homework/homework_1.html)**
   
   **Homework 1 KEY / Example:**
   
   * [Rmd Example]()
   
   * [Html Example]()

   **Related Reading: **

   * [Introduction to R Markdown](https://rmarkdown.rstudio.com/lesson-1.html)
   * [RMarkdown documentation](http://rmarkdown.rstudio.com/)
       + [HTML document options](http://rmarkdown.rstudio.com/html_document_format.html) (global formatting, etc.)
       + [PDF document options](http://rmarkdown.rstudio.com/pdf_document_format.html) (requires LaTeX installation to output PDFs)
       + [Word document options](http://rmarkdown.rstudio.com/word_document_format.html) (but please do not use Word output for this class!)
   * [R Markdown: The Definitive Guide](https://bookdown.org/yihui/rmarkdown/) by Xie, Allaire, and Grolemund, a comprehensive textbook on R Markdown.
   * [Useful RStudio cheatsheets](https://www.rstudio.com/resources/cheatsheets/) on R Markdown, RStudio shortcuts, etc.
   * [Information on the `prettydoc` package](https://yixuan.cos.name/prettydoc/cayman.html) for nicer looking RMarkdown themes
   * [Presentations in RStudio](https://support.rstudio.com/hc/en-us/articles/200486468-Authoring-R-Presentations) for simple presentations
   * [Xaringan](https://github.com/yihui/xaringan) for advanced presentations
   * [`pander` documentation](http://rapporter.github.io/pander/) for making tables, etc.
   * [Shapes and line types](http://www.cookbook-r.com/Graphs/Shapes_and_line_types/) in base R
   * [Color names (PDF)](http://www.stat.columbia.edu/~tzheng/files/Rcolor.pdf) in base R
   


### 2. Visualizing Data

   **Lecture for Week 2:**

   * [Slides for Lecture 2: Plotting with `ggplot2`](https://breonh.github.io/csss_508/lecture/week2/csss_508_Week2_ggplot2.html)
       + [Companion R Script for Lecture 2 slides](https://breonh.github.io/csss_508/lecture/week2/csss_508_week2_rscript_companion.R)
       + [PDF of Lecture 2 slides](https://breonh.github.io/csss_508/lecture/week2/csss_508_Week2_ggplot2.pdf)
       + [Rmd for Lecture 2 slides](https://breonh.github.io/csss_508/lecture/week2/csss_508_Week2_ggplot2.Rmd)
       
   **Lecture Recording: **
   
   [Youtube Link to Week 2 Lecture](https://youtu.be/MKOIEy7tWv4)

   
       
   **Homework 2:**

   * **[Homework 2 Instructions](https://breonh.github.io/csss_508/homework/homework_2.html)**
   
   **Homework 2 KEY / Example:**

   * [Rmd Example]()
   
   * [Html Example]()



   **Further Reading:**

   * Reading: [Visualization chapter in R for Data Science](http://r4ds.had.co.nz/data-visualisation.html)
   * [`ggplot2` Website](https://ggplot2.tidyverse.org/)
   * [`ggplot2` Cheat Sheet](https://github.com/rstudio/cheatsheets/raw/master/data-visualization-2.1.pdf)
   * [The ggplot Flipbook](https://evamaerey.github.io/ggplot_flipbook/ggplot_flipbook_xaringan.html) by [Gina Reynolds](https://github.com/EvaMaeRey)
   * [Cookbook for R graph reference](http://www.cookbook-r.com/Graphs/)
   * [R graph catalog at UBC](http://shiny.stat.ubc.ca/r-graph-catalog/)
   * `ggplot2` add-ons
       + [`ggthemes` package](https://github.com/jrnold/ggthemes)
       + [`cowplot` package](https://cran.r-project.org/web/packages/cowplot/vignettes/introduction.html) for publication ready graphs, multiple plots in single image, etc.
       + [`gganimate` package](https://github.com/dgrtwo/gganimate) for easy animations (saving GIFs requires [ImageMagick](https://www.imagemagick.org/script/index.php) or [GraphicsMagick](http://www.graphicsmagick.org/))
   * [Hadley Wickham on the grammar of graphics](http://vita.had.co.nz/papers/layered-grammar.html)
   * [Tufte in R](http://motioninsocial.com/tufte/) (if that's your sort of thing)
   * Recommended text: [Data Visualization: A Practical Introduction](https://kieranhealy.org/publications/dataviz/) by Kieran Healy



### 3. Manipulating and Summarizing Data

 **Lecture for Week 3:**

   * [Slides for Lecture 3: Manipulating and summarizing data with `dplyr`](https://breonh.github.io/csss_508/lecture/week3/csss_508_week3_dplyr.html)
       + Companion R Script for Lecture 3 slides
       + [PDF of Lecture 3 slides](https://breonh.github.io/csss_508/lecture/week3/csss_508_week3_dplyr.pdf)
       + [Rmd for Lecture 3 slides](https://breonh.github.io/csss_508/lecture/week3/csss_508_week3_dplyr.Rmd)
       
       
  **Lecture Recording: **
   
  [Youtube Link to Week 3 Lecture](https://youtu.be/dG9Jrn2M7oE)

       

**Homework 3:**
       
   * **[Homework 3 Instructions](https://breonh.github.io/csss_508/homework/homework_3.html)**
   * **Homework 3 KEY / Example**

   **Related Reading: **

   * [Data Transformation chapter in R for Data Science](http://r4ds.had.co.nz/transform.html)
   * [A cautionary tale about Excel](http://www.bloomberg.com/news/articles/2013-04-18/faq-reinhart-rogoff-and-the-excel-error-that-changed-history)
   * `dplyr` stuff:
       + [`dplyr` cheatsheets](http://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf) with diagrams to help you remember functions
       + [Introduction to `dplyr`](https://cran.rstudio.com/web/packages/dplyr/vignettes/dplyr.html)
       + [Window functions in `dplyr`](https://cran.r-project.org/web/packages/dplyr/vignettes/window-functions.html)
       + [Joining data in `dplyr`](https://cran.rstudio.com/web/packages/dplyr/vignettes/two-table.html)
       + More advanced joins: [`sqldf` for easy SQL in R](https://cran.r-project.org/web/packages/sqldf/index.html)



### 4. Understanding R Data Structures

 **Lecture for Week 4:**

   * [Slides for Lecture 4: R Data Structures](https://breonh.github.io/csss_508/lecture/week4/csss_508_week4_data_structures.html)
       + [Companion R Script for Lecture 4 slides](https://breonh.github.io/csss_508/lecture/week4/csss_508_week4_rscript_companion.R)
       + [PDF of Lecture 4 slides](https://breonh.github.io/csss_508/lecture/week4/csss_508_week4_data_structures.pdf)
       + [Rmd for Lecture 4 slides](https://breonh.github.io/csss_508/lecture/week4/csss_508_week4_data_structures.Rmd)
       
       


**Homework 4 (Two Options, complete one):**
       
   * **[Homework 4 Template](https://breonh.github.io/csss_508/homework/homework_4.Rmd) (Download this, fill it in, and submit on Canvas)**
   * **Homework 4 [RMD,]() [HTML]()**
   
   * **[Homework 4 Template (More Advanced)](https://breonh.github.io/csss_508/homework/homework_4_alternate.Rmd) (Download this, fill it in, and submit on Canvas)**
   * **Homework 4 (More Advanced) [RMD,]() [HTML]()**
   
  **Lecture Recording: **
   
  [Youtube Link to Week 4 Lecture](https://youtu.be/UGCq9TnE3bg)

       
   
   
  **Lab Recording: **
   
  [Youtube Link to Week 4 Lab](https://youtu.be/zF9fr7X37RE)

       

   **Related Reading: **

 * [Setting up swirl for practice](http://swirlstats.com/students.html)
 * [Data Structures chapter in Advanced R](http://adv-r.had.co.nz/Data-structures.html)



### 5. Importing, Exporting, and Cleaning Data

 **Lecture for Week 5:**

   * [Slides for Lecture 5: Data Import, Export, and Cleaning](https://breonh.github.io/csss_508/lecture/week5/csss_508_week5_import_export.html)
       + [Companion R Script for Lecture 5 slides](https://breonh.github.io/csss_508/lecture/week5/csss_508_week5_rscript_companion.R)
       + [PDF of Lecture 5 slides](https://breonh.github.io/csss_508/lecture/week5/csss_508_week5_import_export.pdf)
       + [Rmd for Lecture 5 slides](https://breonh.github.io/csss_508/lecture/week5/csss_508_week5_import_export.Rmd)

**Homework 5:**
  
   * [Homework 5 Data, **DONT OPEN IN BROWSER**](https://raw.githubusercontent.com/breonh/breonh.github.io/main/csss_508/homework/homework_5/king_county_elections_2016.txt)
  
   * **[Homework 5, Part 1 Template](https://raw.githubusercontent.com/breonh/breonh.github.io/main/csss_508/homework/homework_5.Rmd) (Download this, fill it in, and submit on Canvas)**
   
   **Homework 5 KEY pt. 1:**

   * [Homework 5 part 1 RMD]()
   * [Homework 5 part 1 HTML]()

   **Data From Class: **
   
   [Billboard Data](https://raw.githubusercontent.com/breonh/breonh.github.io/main/csss_508/lecture/week5/data/billboard_2000_raw.csv) 
   
   [One day of SPD Incident Data](https://raw.githubusercontent.com/breonh/breonh.github.io/main/csss_508/lecture/week5/data/Seattle_Police_Department_911_Incident_Response.csv)

 **Lecture Recording: **
   
  [Youtube Link to Week 5 Lecture](https://youtu.be/1ffcMMlQ99w)

 **Lab Recording: **
 
  [Youtube Link to Week 5 Lab](https://youtu.be/MlTnrEjXoYo)


   **Related Reading: **

  * Data import and export:
       + [`readr` documentation](https://cran.r-project.org/web/packages/readr/readr.pdf)
       + [Column types in readr](https://cran.r-project.org/web/packages/readr/vignettes/column-types.html)
       + [Using `dput()` when asking for help](http://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example)
       + [`readxl`](https://readxl.tidyverse.org/) and [`writexl`](https://docs.ropensci.org/writexl/) packages for Excel
   * General data access and cleaning:
       + [New York Times article on "data janitor" work](http://www.nytimes.com/2014/08/18/technology/for-big-data-scientists-hurdle-to-insights-is-janitor-work.html)
       + [Quartz guide to bad data: a must read!](http://qz.com/572338/the-quartz-guide-to-bad-data/)
       + [Lots of resources on survey data sources and analysis in R](http://www.asdfree.com/)
       + [rOpenSci](https://ropensci.org/packages/) (many packages for accessing particular data sources in R)
       + [`qualtrics` API package](https://github.com/jbryer/qualtrics) and [`Rmonkey` for Survey Monkey](https://github.com/cloudyr/Rmonkey)
   * Tidying:
       + [`tidyr` vignette](https://cran.r-project.org/web/packages/tidyr/vignettes/tidy-data.html)
       + [Tidy genomics](http://varianceexplained.org/r/tidy-genomics/) (a walkthough of tidy data preparation and analysis)
   * Dates and times:
       + [`lubridate` vignette](https://cran.r-project.org/web/packages/lubridate/vignettes/lubridate.html)
   * Factors:
       + [Lots on factors from Jenny Bryan](http://stat545-ubc.github.io/block014_factors.html)


### 6. Using Loops 

 **Lecture for Week 6:**

   * [Slides for Lecture 6: Loops](https://breonh.github.io/csss_508/lecture/week6/csss_508_week6_loops.html)
       + [Companion R Script for Lecture 6 slides](https://raw.githubusercontent.com/breonh/breonh.github.io/main/csss_508/lecture/week6/csss_508_week6_rscript_companion.R)
       + [PDF of Lecture 6 slides](https://breonh.github.io/csss_508/lecture/week6/csss_508_week6_loops.pdf)
       + [Rmd for Lecture 6 slides](https://breonh.github.io/csss_508/lecture/week6/csss_508_week6_loops.Rmd)

 **Homework 5, part 2:**
       
   * **[Homework 5, part 2 Template](https://breonh.github.io/csss_508/homework/homework_5.Rmd)**
   * **Homework 5 KEY:**
   
      + [RMD]()
      
      + [HTML]()

 **Lecture Recording: **
   
  [Youtube Link to Week 6 Lecture](https://youtu.be/_HfZhgP4xu8)

 **Lab Recording **
 
  [Youtube Link to Week 6 Lab](https://youtu.be/SsXH03_uU_U)

### 7. Writing Functions

 **Lecture for Week 7:**

   * [Slides for Lecture 7: Loops](https://breonh.github.io/csss_508/lecture/week7/csss_508_week7_vectorization.html)
       + [Companion R Script for Lecture 7 slides](https://raw.githubusercontent.com/breonh/breonh.github.io/main/csss_508/lecture/week7/csss_508_week7_rscript_companion.R)
       + [PDF of Lecture 7 slides](https://breonh.github.io/csss_508/lecture/week7/csss_508_week7_vectorization.pdf)
       + [Rmd for Lecture 7 slides](https://breonh.github.io/csss_508/lecture/week7/csss_508_week7_vectorization.Rmd)

 **Homework 6, part 1:**
       
   * **[Homework 6, part 1 Template](https://raw.githubusercontent.com/breonh/breonh.github.io/main/csss_508/homework/homework_6/homework_6.Rmd)**
   
   * **Homework 6, part 1 KEY**
   
   * **[Homework 6 Data File](https://s3.amazonaws.com/pronto-data/open_data_year_one.zip) ** 

 **Lecture Recording:**
 
 [Youtube Link to Week 7 Lecture](https://youtu.be/xRMYFiJzQPg)
 
 **Lab Recording:**
 
 [Youtube Link to Week 7 Lab](https://youtu.be/_RZ9OPznDf4)


 **Related Reading: **

   * [The R Inferno by Patrick Burns [PDF]](http://www.burns-stat.com/pages/Tutor/R_inferno.pdf): "Circles" 2, 3, and 4 are relevant after this week's material, and Circle 8 covers a lot of miscellaneous R weird things that may trip you up.
   * [Reference material on writing functions](http://r4ds.had.co.nz/functions.html) with lots of examples
   * [Code style guide](http://adv-r.had.co.nz/Style.html) for writing functions, etc.
   * [R, the master troll of statistical languages](http://www.talyarkoni.org/blog/2012/06/08/r-the-master-troll-of-statistical-languages/) (to read if you feel a bit frustrated!)
   * [Tutorial on `purrr` ](https://jennybc.github.io/purrr-tutorial/) for vectorization by Jenny Bryan.



### 8. Working with Text Data

 **Lecture for Week 8:**

   * [Slides for Lecture 8: Working with Strings and Character Data](https://breonh.github.io/csss_508/lecture/week8/csss_508_week8_strings.html)
       + [Companion R Script for Lecture 8 slides](https://breonh.github.io/csss_508/lecture/week8/csss_508_week8_rscript_companion.R)
       + [PDF of Lecture 8 slides](https://breonh.github.io/csss_508/lecture/week8/csss_508_week8_strings.pdf)
       + [Rmd for Lecture 8 slides](https://breonh.github.io/csss_508/lecture/week8/csss_508_week8_strings.Rmd)

 **Homework 6, part 2:**
       
   * **[Homework 6 Template]()**
  
 **Homework 6, part 2 KEY:**
   
   * [HTML]()
   * [RMD]()

   **Data From Class: **
   
   [Seattle Restaurants](https://github.com/breonh/breonh.github.io/blob/main/csss_508/lecture/week8/restaurants.csv)

   **Lecture Recording: **

   [Youtube Link to Week 8 Lecture](https://youtu.be/vdJhtKOs3kA)
   
   **Lab Recording: **
   
   [Youtube Link to Week 8 Lab](https://youtu.be/jcLLtvupfU8)

 **Related Reading: **

   * [RStudio Cheat Sheet for Strings](https://github.com/rstudio/cheatsheets/blob/main/strings.pdf)
   * [`stringr` vignette](https://cran.r-project.org/web/packages/stringr/vignettes/stringr.html)
   * [Site for regular expression testing](http://regexr.com/)  with a good cheatsheet and hover explanations
   * [Blog post explaining `paste()`](https://trinkerrstuff.wordpress.com/2013/09/15/paste-paste0-and-sprintf-2) for combining strings


### 9. Working with Geographical Data

 **Lecture for Week 9:**

   * [Slides for Lecture 9: Mapping with ggplot2 and sf](https://breonh.github.io/csss_508/lecture/week9/CSSS508_Week9_mapping.html)
       + [Companion R Script for Lecture 9 slides](https://breonh.github.io/csss_508/lecture/week9/csss_508_week9_rscript_companion.R)
       + [PDF of Lecture 9 slides](https://breonh.github.io/csss_508/lecture/week9/CSSS508_Week9_mapping.pdf)
       + [Rmd for Lecture 9 slides](https://breonh.github.io/csss_508/lecture/week9/CSSS508_Week9_mapping.Rmd)

   **Optional Homework 7:**
       
   * **[Optional Homework 7 Template](https://breonh.github.io/csss_508/homework/homework_7.Rmd)**
   * **Homework 7 KEY**
     + [RMD]()
     + [HTML]()

  **Lecture Recording: **
  
  [Youtube Link to Week 9 Recording](https://youtu.be/ZVvbiHOCRPs)

 **Related Reading: **

   * Suggested text: [Applied Spatial Data Analysis with R](http://www.springer.com/us/book/9781461476177)  by Bivand et al.
   * [RSpatial.org](http://www.rspatial.org/index.html): Massive resource for spatial analysis in R
   * [`ggmap` package examples](https://github.com/dkahle/ggmap)
   * [More in depth `ggmap` examples](http://vita.had.co.nz/papers/ggmap.pdf)
   * [`ggrepel` package vignette](https://cran.r-project.org/web/packages/ggrepel/vignettes/ggrepel.html)
   * [`sf` Vignette: Overview](https://cran.r-project.org/web/packages/sf/vignettes/sf1.html)
   * [`sf` Home Page](https://r-spatial.github.io/sf/)
   * [Tyler Morgan Wall's 3D Mapping and Visualization Masterclass](https://github.com/tylermorganwall/MusaMasterclass)



### 10. Reproducibility and Model Results

 **Lecture for Week 10:**

   * [Slides for Lecture 10: Reproducibility and Model Results](https://breonh.github.io/csss_508/lecture/week10/csss_508_Week10_model_results.html)
       + [Companion R Script for Lecture 10 slides](https://breonh.github.io/csss_508/lecture/week10/csss_508_week10_rscript_companion.R)
       + [PDF of Lecture 10 slides](https://breonh.github.io/csss_508/lecture/week10/csss_508_Week10_model_results.pdf)
       + [Rmd for Lecture 10 slides](https://breonh.github.io/csss_508/lecture/week10/csss_508_Week10_model_results.Rmd)


  **Lecture Recording: **
  
  [Youtube Link to Week 10 Recording](https://youtu.be/b9Fe6-V2vQc)

 **Related Reading: **

   * [Good Enough Practices in Scientific Computing](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005510)
   * [Initial Steps Toward Reproducible Research](https://kbroman.org/steps2rr/) by Karl Broman
   * [The Plain Person's Guide to Plain Text Social Science](http://plain-text.co) by Kieran Healy
   * R Packages:
      + [`huskydown`](https://github.com/benmarwick/huskydown)
      + [`rrtools`](https://github.com/benmarwick/rrtools)
      * [`broom` vignette](https://cran.r-project.org/web/packages/broom/vignettes/broom.html)
      * [`ggeffects` vignette](https://cran.r-project.org/web/packages/ggeffects/vignettes/marginaleffects.html)
      * [`sjPlot` home page](http://www.strengejacke.de/sjPlot/)
   * [Overleaf online LaTeX editor](http://www.overleaf.com/)


















































This project is maintained by [Breon Haskett](https://github.com/breonh) and includes materials from [Chuck Lanfear](https://github.com/clanfear) with permission.

Cherry blossom photo credit: [Mark Stone](https://www.washington.edu/marketing/people/mark-stone/)