---
title: "<br> Week 1: Expectations"
subtitle: "POLS 249 - HSTCMP 249 - SOC 266"
author: "Breon Haskett"
date: "January 07, 2022"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: xaringan-themer.css
    nature:
      highlightStyle: tomorrow-night-bright
      highlightLines: true
      countIncrementalSlides: false
      titleSlideClass: ["center","top"]
---

```{r, message=FALSE, echo=FALSE}
library(tidyverse)
library(gt)
```




# Course Goals 

* Social science methods (make you **think critically**)
* Make you **engaged members of the polity**




---
# Assignment Breakdown 

```{r grade breakdown table, echo = FALSE}

data.frame("Assignments" = c("Midterm Exam",
                             "Reading Responses",
                             "Discussion Section Participation and Quizzes",
                             "Final Exam",
                             "Term Paper"),
           "Breakdown" = c(.2, .1, .15, .25, .3)) %>% 
  arrange(-Breakdown) %>% 
  gt(rowname_col = "Assignments") %>% 
  fmt_percent(columns = "Breakdown", decimals = 0) %>% 
  tab_header(title = "Is this going to be on the test??")




```











